#!/usr/bin/env bash
#script that displays best school 10 times using until

i=0
 until false; do
  echo "Best School" 
  ((i++))
  if [[ $i -lt 10 ]]; then
  continue 
   else
      break
      fi
    done
    