#!/usr/bin/env bash
#display best school 10 times,for 9th iteration display best school and then hi

i=1
 while [ "$i" -lt 11 ]; do
   echo "Best School"
    # if statement that prints Hi when i is 9
    if [ "$i" -eq 9 ]; then
      echo "Hi"
        fi
    ((i++))
 done 
 