#!/usr/bin/env bash
#displays good luck for the 4th iteration
#displays bad luck for the 8th iteration
#displays good luck for the other iterations
#using while,if,elif and else.

i=1
while [ "$i" -lt 11 ]; do
  # if the value is 4:bad luck
   if [ "$i" -eq 4 ]; then
   echo "bad luck"
   elif [ "$i" -eq 8 ]; then
   echo "good luck"
    else 
    echo "Best School"
     fi 
  ((i++))
 done 
 