#!/usr/bin/env bash
#script that displays numbers from 1 to 20 using while and case

i=1
while [ "$i" -lt 21 ]; do
  # if the value is 4:bad luck
   case "$i" in
     4) echo "$i"
           echo "bad luck from China"
            ;;
	 9) echo "$i"
             echo "bad luck from Japan"
		 ;;
	     17) echo "$i"
		  echo "bad luck from Italy"
		;;

		*)
		echo "$i"
              ;;
	esac

		((i++))
     done
     